version: '3'

services:
  db:
    image: mysql:8.0
    container_name: dev-db-socialmedia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialmedia
      MYSQL_USER: mariomans
      MYSQL_PASSWORD: root
      MYSQL_USER_PRIVILEGES: "ALL PRIVILEGES"
    ports:
      - 3308:3306
    volumes:
      - ./db_data:/var/lib/mysql
